language: generic
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# before install -> chmod
before_install: 
  - chmod +x gradlew 

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - shineest96@gmail.com 
      
before_deploy:
  - zip -r Spring *
  - mkdir -p deploy
  - mv Spring.zip deploy/Spring.zip


deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: shineest # 6-3-3에서 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    on:
      repo: weelleekid/proj1 #Github 주소
      branch: master
     
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: shineest # 6-3-3에서 생성한 S3 버킷
    key: Spring.zip # S3 버킷에 저장된 springboot-webservice.zip 파일을 EC2로 배포
    bundle_type: zip
    application: Spring # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: Spring-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: weelleekid/proj1
      branch: master
  

