spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---  
# 상단은 공통 영역이며, 하단이 각 profile의 설정 영역
# 하단 영역이 상단을 덮어 씌움
spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:test
    data: classpath:data-h2.sql # 시작할때 실행시킬 script
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  
    #spring.datasource.url 설정 -> database url, default: random when build